apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vprofile
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Mohamed-Elsayed-Hussein/Deploying-Vprofile-app.git"
    path: application-CD
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
