apiVersion: v1
data:
  JDBC_URL: amRiYzpteXNxbDovL2RiLmRiLnN2Yy5jbHVzdGVyLmxvY2FsOjMzMDYvYWNjb3VudHM=
  MEMCACHED_ACTIVE_HOST: bWMubWMuc3ZjLmNsdXN0ZXIubG9jYWw=
  MEMCACHED_STANDBY_HOST: bWMubWMuc3ZjLmNsdXN0ZXIubG9jYWw=
  RABBITMQ_ADDRESS: cm1xLnJtcS5zdmMuY2x1c3Rlci5sb2NhbA==
kind: Secret
metadata:
  name: app-secret
  namespace: app
